default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: sunny
  password: labber
  database: postgress

development:
  <<: *default
  database: your_database_name_development

test:
  <<: *default
  database: your_database_name_test

production:
  <<: *default
  database: your_database_name_production
  username: your_production_username
  password: your_production_password